import React from 'react';
import { Target, ShieldCheck, Leaf } from 'lucide-react';
import { PlanMetadata, Action } from './types';

export const plansMetadata: PlanMetadata[] = [
    { id: 'saude_ona', name: 'Sáude (ONA)', pa_code: '10717', subtitle: 'Rumo à Acreditação ONA', icon: <Target className="w-6 h-6 sm:w-7 sm:h-7 md:w-8 md:h-8 text-white"/>, link: 'https://sistemafiea.sysepa.com.br/epa/incluir_plano_acao.php?codigo=10717' },
    { id: 'sst_iso45001', name: 'SST (ISO 45001)', pa_code: '12451', subtitle: 'Certificação em Saúde e Segurança', icon: <ShieldCheck className="w-6 h-6 sm:w-7 sm:h-7 md:w-8 md:h-8 text-white"/>, link: 'https://sistemafiea.sysepa.com.br/epa/incluir_plano_acao.php?codigo=12451' },
    { id: 'ambiental_iso14001', name: 'Ambiental (ISO 14001)', pa_code: '13880', subtitle: 'Certificação em Gestão Ambiental', icon: <Leaf className="w-6 h-6 sm:w-7 sm:h-7 md:w-8 md:h-8 text-white"/>, link: 'https://sistemafiea.sysepa.com.br/epa/incluir_plano_acao.php?codigo=13880' },
];

export const allSampleData: Record<string, Action[]> = {
    saude_ona: [
        { id: 26204, action: "Definir e implementar sistemática de acompanhamento das comissões e diretrizes institucionais (Plano de Segurança do Paciente e PCIRAS)", responsible: "Mylena Soares", sector: "Segurança e Saúde para Indústria", startDate: "2025-01-01", endDate: "2025-11-07", status: "Planejado", followUp: "Sem Acompanhamentos" },
        { id: 26205, action: "Fortalecer método de análise, classificação e tratativa de incidentes do Núcleo de Segurança do Paciente (NSP)", responsible: "Mylena Soares", sector: "Segurança e Saúde para Indústria", startDate: "2025-01-01", endDate: "2025-10-08", status: "Concluído", followUp: "Sem Acompanhamentos" },
        { id: 26206, action: "Assegurar o acompanhamento das ações previstas para o monitoramento da governança clínica, promovendo ações de melhoria", responsible: "Carolina Albuquerque", sector: "Segurança e Saúde para Indústria", startDate: "2025-01-01", endDate: "2025-10-31", status: "Planejado", followUp: "Sem Acompanhamentos" },
        { id: 26207, action: "Implementar sistema de gerenciamento de protocolos clínicos e assistenciais", responsible: "Marcia Casado", sector: "Unidade Sesi Cambona", startDate: "2025-01-01", endDate: "2025-11-07", status: "Planejado", followUp: "Sem Acompanhamentos" },
        { id: 26208, action: "Assegurar a realização de testes de avaliação de eficácia de todos os planos de contingência implementados nas unidades de saúde, bem como a implementação das ações de melhoria", responsible: "Carolina Albuquerque", sector: "Segurança e Saúde para Indústria", startDate: "2025-01-01", endDate: "2025-10-31", status: "Em Andamento", followUp: "Sem Acompanhamentos" },
        { id: 26209, action: "Assegurar o cumprimento das ações previstas no Manual de Auditorias definido pela organização, assegurando registros das auditorias realizadas, bem como tratativa das não conformidades encontradas durante as auditorias", responsible: "Pitter Silva", sector: "Processos", startDate: "2025-01-01", endDate: "2025-10-31", status: "Em Andamento", followUp: "03/09: Orientado revisão do manual de auditoria com ferramenta própria e a seguir o escopo do manual. Orientado reunião do NSP às quartas e sobre as notificações de auditorias. Realizar até o final do mês." },
        { id: 26210, action: "Analisar e assegurar o cumprimento das ações definidas no Programa de Controle de Infecções, como a realização de visitas técnicas", responsible: "Nice Cabral", sector: "Unidade Sesi Cambona", startDate: "2025-01-01", endDate: "2025-11-30", status: "Em Andamento", followUp: "08/10: Orientado atualizar PCIRAS para 2026 com novas datas de visitas técnicas. 23/10: Ficou acordada na reunião de PCIRAS que essa ação será reprogramada para que a sua conclusão seja até o dia 30/11." },
        { id: 26211, action: "Assegurar que os procedimentos para controle de rastreabilidade de medicamentos e anestésicos sejam realizados, implementando barreiras para o registro das informações", responsible: "Fania Silva", sector: "Segurança e Saúde para Indústria", startDate: "2025-01-01", endDate: "2025-10-31", status: "Em Andamento", followUp: "O manual enviado já define o registro em prontuário. Será implementada uma rotina de avaliação dos registros pela comissão de prontuário, incluindo nos formulários de avaliação." },
        { id: 26212, action: "Assegurar implementação das ações de melhoria planejadas para a sistemática de registros e evoluções pelos profissionais da Odontologia, assegurando a completude e qualidade das informações registradas no sistema Lifeone", responsible: "Marcia Casado", sector: "Unidade Sesi Cambona", startDate: "2025-01-01", endDate: "2025-10-31", status: "Em Andamento", followUp: "Revisar a adequação do formulário de registro de limpeza, checar o manual e cronograma, e verificar a metodologia de registro. Reunir com a equipe para treinar a adequação." },
        { id: 26213, action: "Considerar a avaliação da sistemática utilizada para rastreabilidade dos materiais estéreis utilizados nos pacientes, assegurando a identificação dos materiais utilizados em cada procedimento, fortalecendo a segurança do paciente", responsible: "Fania Silva", sector: "Segurança e Saúde para Indústria", startDate: "2025-01-01", endDate: "2025-10-31", status: "Em Andamento", followUp: "Status: Não existe rastreamento por material; kits retornam de forma aleatória. Já existe uma planilha na CME que informa ciclos e saída." },
        { id: 26240, action: "Unid. Tabuleiro: Assegurar que a frequência e os registros das atividades de limpeza realizadas nas áreas sejam atendidos e registrados corretamente, conforme previsto no Manual de Higienização da organização", responsible: "Fania Silva", sector: "Segurança e Saúde para Indústria", startDate: "2025-01-01", endDate: "2025-10-31", status: "Em Andamento", followUp: "O manual enviado já define o registro em prontuário. Será implementada uma rotina de avaliação dos registros pela comissão de prontuário, incluindo nos formulários de avaliação." },
        { id: 26243, action: "Assegurar o acompanhamento das ações propostas pelas comissões implementadas, bem como assegurar cumprimento das diretrizes previstas nos documentos institucionais, como exemplo Plano de Segurança do Paciente e Programa de Controle de Infecções Relacionadas à Assistência à Saúde", responsible: "Mylena Soares", sector: "Segurança e Saúde para Indústria", startDate: "2025-01-01", endDate: "2025-10-31", status: "Concluído", followUp: "Sem Acompanhamentos" },
        { id: 26275, action: "Promover o gerenciamento dos protocolos clínicos e assistenciais implementados", responsible: "Marcia Casado", sector: "Unidade Sesi Cambona", startDate: "2025-01-01", endDate: "2025-10-31", status: "Em Andamento", followUp: "Sem Acompanhamentos" },
        { id: 26334, action: "Realizar treinamento com os colaboradores do SSI sobre a utilização do EPA", responsible: "Erik Santos", sector: "Segurança e Saúde para Indústria", startDate: "2025-01-01", endDate: "2025-10-31", status: "Em Andamento", followUp: "Sem Acompanhamentos" },
    ],
    sst_iso45001: [
        { id: 1, action: "Realizar diagnóstico de perigos e riscos", responsible: "Mariana Alves", sector: "SST", startDate: "2024-06-01", endDate: "2024-07-30", status: "Em Andamento", followUp: "Mapeamento de riscos concluído em 5 dos 8 setores. Próximos passos: consolidação do relatório." },
        { id: 2, action: "Formar a Comissão Interna de Prevenção de Acidentes (CIPA)", responsible: "João Ferreira", sector: "RH", startDate: "2024-05-15", endDate: "2024-06-20", status: "Concluído", followUp: "Membros da CIPA eleitos e empossados. Reuniões mensais agendadas." },
        { id: 3, action: "Adquirir Equipamentos de Proteção Individual (EPIs)", responsible: "Carlos Rodrigues", sector: "Compras", startDate: "2024-07-01", endDate: "2024-08-15", status: "Planejado", followUp: "Levantamento de necessidades de EPIs em andamento junto aos setores." },
    ],
    ambiental_iso14001: [
        { id: 1, action: "Elaborar a Política de Gestão Ambiental", responsible: "Sofia Bernardes", sector: "Sustentabilidade", startDate: "2024-06-10", endDate: "2024-07-10", status: "Concluído", followUp: "Política elaborada, aprovada e comunicada a todos os colaboradores." },
        { id: 2, action: "Mapear aspectos e impactos ambientais", responsible: "Ricardo Gomes", sector: "Engenharia", startDate: "2024-07-11", endDate: "2024-09-20", status: "Em Andamento", followUp: "Levantamento de campo iniciado. Foco inicial em consumo de água e energia." },
        { id: 3, action: "Criar programa de coleta seletiva e gestão de resíduos", responsible: "Ana Pereira", sector: "Operações", startDate: "2024-08-01", endDate: "2024-10-30", status: "Planejado", followUp: "Orçamentos para coletores e parceiros de reciclagem sendo analisados." },
    ]
};